<?php

use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Мистраль рис',
                'alias' => 'mistral_basmati_',
                'price' => 75,
                'old_price' => 55,
                'status' => '1',
                'keywords' => 'рис белый мистраль',
                'description' => 'Мистраль рис белый "Басмати 1кг',
                'img' => 'mistral_basmati.jpg',
                'hit' => '1',
            ],
            [
                'id' => '2',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Мистраль пшено',
                'alias' => 'мисталь рис',
                'price' => 200,
                'old_price' => 200,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Мистраль пшено 1кг',
                'img' => 'mistral_psheno.jpg',
                'hit' => '1',
            ],
            [
                'id' => '3',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => '350 Гречка',
                'alias' => '350 Гречка',
                'price' => 100,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'крупа гречка',
                'description' => 'Гречневая крупа 1кг',
                'img' => '365_grechka.jpg',
                'hit' => '1',
            ],
            [
                'id' => '4',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Геркулес',
                'alias' => 'крупа геркулес ',
                'price' => 120,
                'old_price' => 130,
                'status' => '1',
                'keywords' => 'экстра геркулес дешего',
                'description' => 'Геркулес Экстра 1кг',
                'img' => 'ekstra_gerkules.jpg',
                'hit' => '1',
            ],


            [
                'id' => '5',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Сахар рафинад 1 кг',
                'alias' => 'Сахар рафинад дешго химки',
                'price' => 320,
                'old_price' => 220,
                'status' => '1',
                'keywords' => 'сахар рафинад русский сахар',
                'description' => 'Русский сахар рафинад 1кг',
                'img' => 'rafinad1.jpg',
                'hit' => '1',
            ],
            [
                'id' => '6',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Соль',
                'alias' => 'соль банка 1кг химки',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'соль банка 1кг химки',
                'description' => 'Соль поварная 1кг банка',
                'img' => 'ekstra_sold.jpg',
                'hit' => '0',
            ],


            [
                'id' => '7',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Krušovice (Крушовице) пиво светлое 0,5 л',
                'alias' => 'KrushoviceSvetSteklo',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое крущевице крущовице Krušovice  ',
                'description' => 'Krušovice (Крушовице) пиво светлое 0,5 л',
                'img' => 'krushovice05s.jpg',
                'hit' => '0',
            ],
            [
                'id' => '8',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Krušovice (Крушовице) пиво темное 0,5 л',
                'alias' => 'KrushoviceDarkSteklo',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво темное крущевице крущовице Krušovice  ',
                'description' => 'Krušovice (Крушовице) пиво темное 0,5 л',
                'img' => 'krushoviceT05s.jpg',
                'hit' => '0',
            ],
            [
                'id' => '9',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Heineken (Хейнекен) пиво светлое 0,5 л',
                'alias' => 'HeinekenSteklo',
                'price' => 70,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Хейнекен Heineken',
                'description' => 'Heineken (Хейнекен) пиво светлое 0,5 л',
                'img' => 'heneken05s.jpg',
                'hit' => '0',
            ],
            [
                'id' => '10',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Heineken (Хейнекен) пиво светлое 0,5 л',
                'alias' => 'Heineken',
                'price' => 70,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Хейнекен Heineken',
                'description' => 'Heineken (Хейнекен) пиво светлое 0,5 л ж/б',
                'img' => 'heineken05ba.jpg',
                'hit' => '0',
            ],


            [
                'id' => '11',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Heineken (Хейнекен) пиво светлое 0,33 л',
                'alias' => 'Heineken033',
                'price' => 70,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Хейнекен Heineken 0,33 л',
                'description' => 'Heineken (Хейнекен) пиво светлое 0,33 л',
                'img' => 'haineken033.jpg',
                'hit' => '0',
            ],
            [
                'id' => '12',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Охота крепкое светлое пиво 0,9 л',
                'alias' => 'Oxota',
                'price' => 110,
                'old_price' => 105,
                'status' => '1',
                'keywords' => 'Пиво светлое Охота крепкое 1л 1 л баклашка дешего',
                'description' => 'Охота крепкое светлое пиво 0,9 л',
                'img' => 'oxota09.jpg',
                'hit' => '0',
            ],

            [
                'id' => '13',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Кроненбург 1664 (Kronenbourg 1664) светлое 0,5 л',
                'alias' => 'Kronenbourg',
                'price' => 110,
                'old_price' => 105,
                'status' => '1',
                'keywords' => 'Пиво светлое Кроненбург Kronenbourg 1664',
                'description' => 'Пиво Кроненбург 1664 (Kronenbourg 1664) светлое 0,5 л',
                'img' => 'kronenburg.jpg',
                'hit' => '0',
            ],

            [
                'id' => '14',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Кроненбург бланк 1664 (Kronenbourg blank 1664) светлое 0,5 л',
                'alias' => 'KronenbourgBlank',
                'price' => 110,
                'old_price' => 105,
                'status' => '1',
                'keywords' => 'Пиво светлое бланк Кроненбург Kronenbourg blank 1664',
                'description' => 'Пиво Кроненбург бланк 1664 (Kronenbourg blank 1664) светлое 0,5 л',
                'img' => 'kronenburgBlank.jpg',
                'hit' => '0',
            ],

            [
                'id' => '15',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Velkopopovický Kozel (Козел) 0,5 л',
                'alias' => 'KozelSvetloe',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Velkopopovický Kozel велкопопвицкий (Козел) 0,5 л',
                'description' => 'Пиво светлое Velkopopovický Kozel (Козел) 0,5 л',
                'img' => 'kozel05.jpg',
                'hit' => '0',
            ],

            [
                'id' => '16',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Velkopopovický Kozel (Козел) 0,5 л ж/б',
                'alias' => 'KozelTemn',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Velkopopovický Kozel железная банка велкопопвицкий (Козел) 0,5 л',
                'description' => 'Пиво светлое Velkopopovický Kozel (Козел) 0,5 л ж/б',
                'img' => 'kozel05B.jpg',
                'hit' => '0',
            ],
            [
                'id' => '17',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво темное Velkopopovický Kozel (Козел) 0,5 л ж/б',
                'alias' => 'KozelBAN',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво темное Velkopopovický Kozel железная банка велкопопвицкий (Козел) 0,5 л',
                'description' => 'Пиво темное Velkopopovický Kozel (Козел) 0,5 л ж/б',
                'img' => '3249575H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '18',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Kilikia (Киликия) 0,5 л',
                'alias' => 'Kilikia',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Kilikia армянское 0,5 л',
                'description' => 'Пиво светлое Kilikia (Киликия) 0,5 л',
                'img' => 'kilikia.jpg',
                'hit' => '0',
            ],
            [
                'id' => '19',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Holsten (Холстен) 0,5 л',
                'alias' => 'Holsten',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Holsten Холстен 0,5 л',
                'description' => 'Пиво светлое Holsten (Холстен) 0,5 л ж/б',
                'img' => '3307367H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '20',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое балтика № 3 0,5 л',
                'alias' => 'Baltika3',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое балтика Baltika № 3 0,5 л',
                'description' => 'Пиво светлое балтика № 3 0,5 л ж/б',
                'img' => '3307370H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '21',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое балтика № 7 0,5 л',
                'alias' => 'Baltika7G',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое балтика Baltika № 7 0,5 л',
                'description' => 'Пиво светлое балтика № 7 0,5 л ж/б',
                'img' => '3307381H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '22',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво живое Калуга 0,5 л',
                'alias' => 'Kaluga',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво Kaluga живое Калуга 0,5 л',
                'description' => 'Пиво живое Калуга 0,5 л',
                'img' => '3317184H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '23',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Bud (Бад) 0,5 л',
                'alias' => 'BudSt',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Bud (Бад) 0,5 л',
                'description' => 'Пиво светлое Bud (Бад) 0,5 л',
                'img' => '3349776H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '24',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Bud (Бад) 0,5 л ж/б',
                'alias' => 'BudB',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Bud (Бад) 0,5 л железная банка',
                'description' => 'Пиво светлое Bud (Бад) 0,5 л ж/б',
                'img' => '3349777H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '25',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Efes (Эфес) 0,5 л ж/б',
                'alias' => 'EfesB',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Efes (Эфес) 0,5 л ж/б',
                'description' => 'Пиво светлое Efes (Эфес) 0,5 л ж/б',
                'img' => '3317185H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '26',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Крым 0,9 л',
                'alias' => 'Krim',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво светлое Крым 0,9 л Баклашка пузырь',
                'description' => 'Пиво светлое Крым 0,9 л',
                'img' => '3284032H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '27',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Хамовники 0,5 л',
                'alias' => 'Khamovniki',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво Хамовники 0,5 л стекляная бутылка',
                'description' => 'Пиво Хамовники 0,5 л',
                'img' => '3324855H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '28',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Золотая Бочка классическое 0,5 л',
                'alias' => 'Bochka',
                'price' => 62,
                'old_price' => 60,
                'status' => '1',
                'keywords' => 'Пиво Золотая Бочка классическое 0,5 л железная банка',
                'description' => 'Пиво Золотая Бочка классическое 0,5 л ж/б',
                'img' => '3320298H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '30',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Fax (Факс) пиво светлое 0,9 л',
                'alias' => 'Fax09',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Fax факс железная банка 1л 0,9л  л',
                'description' => 'Пиво светлое Fax факс железная банка 0,9 л ж/б',
                'img' => '3329298H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '31',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Fax (Факс) пиво светлое 0,5 л',
                'alias' => 'Fax05B',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Fax факс железная банка 0,5л 0,4л  л',
                'description' => 'Пиво светлое Fax факс железная банка 0,5 л ж/б',
                'img' => '3349959H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '32',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Löwenbräu (Ловенбрау) пиво светлое 0,5 л',
                'alias' => 'lowenbrauB',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Löwenbräu (Ловенбрау) пиво светлое 0,5 л железная банка',
                'description' => 'Löwenbräu (Ловенбрау) пиво светлое 0,5 л ж/б',
                'img' => '3349780H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '33',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Essa (Эсса) грейпфрут пивной напиток 0,5 л',
                'alias' => 'EssaGr',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Essa (Эсса) грейпфрут пивной напиток 0,5 л стекляная бутылка',
                'description' => 'Essa (Эсса) грейпфрут пивной напиток 0,5 л',
                'img' => '3372121H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '34',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Essa (Эсса) лайм пивной напиток 0,5 л',
                'alias' => 'EssaLm',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Essa (Эсса) лайм пивной напиток 0,5 л стекляная бутылка',
                'description' => 'Essa (Эсса) лайм пивной напиток 0,5 л',
                'img' => '3372122H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '35',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Hoegaarden (Хугарден) пиво нефильтрованное 0,5',
                'alias' => 'HoegaardenS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Hoegaarden (Хугарден) пиво нефильтрованное 0,5',
                'description' => 'Hoegaarden (Хугарден) пиво нефильтрованное 0,5',
                'img' => '3349779H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '36',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Старый Мельник Мягкое 0,5 л',
                'alias' => 'MelnikS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво Старый Мельник Мягкое 0,5 л',
                'description' => 'Пиво Старый Мельник Мягкое 0,5 л',
                'img' => '3372127H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '37',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Reeds (Редс)  пивной напиток 0,5 л',
                'alias' => 'ReedsS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Reeds (Риидс)  пивной напиток 0,5 л',
                'description' => 'Reeds (Редс)  пивной напиток 0,5 л',
                'img' => '3372124H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '38',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Жигули Бархатное темное 0,5',
                'alias' => 'jiguliTS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво Жигули Бархатное темное 0,5',
                'description' => 'Пиво Жигули Бархатное темное 0,5',
                'img' => '3377970H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '39',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво Жигули Барное 0,5',
                'alias' => 'jiguliB',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво Жигули Барное 0,5',
                'description' => 'Пиво Жигули Барное 0,5',
                'img' => '3396865H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '40',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Garage (Гараж) Вишня пивной напиток 0,5 л',
                'alias' => 'GarageChB',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Garage (Гараж) Вишня пивной напиток 0,5 л',
                'description' => 'Garage (Гараж) Вишня пивной напиток 0,5 л',
                'img' => '3378777H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '41',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво темное Leffe  0.5 л',
                'alias' => 'LeffeTS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво темное Leffe  0.5 л',
                'description' => 'Пиво темное Leffe  0.5 л',
                'img' => '3402139H.jpg',
                'hit' => '0',
            ],
            [
                'id' => '42',
                'category_id' => '3',
                'brand_id' => '8',
                'title' => 'Пиво светлое Leffe  0.5 л',
                'alias' => 'LeffeSS',
                'price' => 80,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'Пиво светлое Leffe  0.5 л',
                'description' => 'Пиво светлое Leffe  0.5 л',
                'img' => '3402138H.jpg',
                'hit' => '0',
            ],

        ];

        DB::table('products')->insert($data);
    }
}
