<?php

use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Мистраль рис',
                'alias' => 'casio-mrp-700-1avef',
                'price' => 75,
                'old_price' => 55,
                'status' => '1',
                'keywords' => 'рис белый мистраль',
                'description' => 'Мистраль рис белый "Басмати 1кг',
                'img' => 'mistral_basmati.jpg',
                'hit' => '1',
            ],
            [
                'id' => '2',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Мистраль пшено',
                'alias' => 'мисталь рис',
                'price' => 200,
                'old_price' => 200,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Мистраль пшено 1кг',
                'img' => 'mistral_psheno.jpg',
                'hit' => '1',
            ],
            [
                'id' => '3',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => '350 Гречка',
                'alias' => '350 Гречка',
                'price' => 100,
                'old_price' => 75,
                'status' => '1',
                'keywords' => 'крупа гречка',
                'description' => 'Гречневая крупа 1кг',
                'img' => '365_grechka.jpg',
                'hit' => '1',
            ],
            [
                'id' => '4',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Геркулес',
                'alias' => 'крупа геркулес ',
                'price' => 120,
                'old_price' => 130,
                'status' => '1',
                'keywords' => 'экстра геркулес дешего',
                'description' => 'Геркулес Экстра 1кг',
                'img' => 'ekstra_gerkules.jpg',
                'hit' => '1',
            ],


            [
                'id' => '5',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Сахар рафинад 1 кг',
                'alias' => 'Сахар рафинад дешго химки',
                'price' => 320,
                'old_price' => 220,
                'status' => '1',
                'keywords' => 'сахар рафинад русский сахар',
                'description' => 'Русский сахар рафинад 1кг',
                'img' => 'rafinad1.jpg',
                'hit' => '1',
            ],
            [
                'id' => '6',
                'category_id' => '2',
                'brand_id' => '5',
                'title' => 'Соль',
                'alias' => 'соль банка 1кг химки',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'соль банка 1кг химки',
                'description' => 'Соль поварная 1кг банка',
                'img' => 'ekstra_sold.jpg',
                'hit' => '1',
            ],


            [
                'id' => '7',
                'category_id' => '10',
                'brand_id' => '3',
                'title' => 'Q&Q Water Resistance VFQ - Кью Кью Вотер Резинтент ФВ',
                'alias' => 'q-and-q-q956j302y',
                'price' => 320,
                'old_price' => 220,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '1',
            ],
            [
                'id' => '8',
                'category_id' => '10',
                'brand_id' => '4',
                'title' => 'Royal London 41040-01VQ - Ройял Лондон Часы 410 ВКью',
                'alias' => 'royal-london-41040-01',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '1',
            ],
            [
                'id' => '9',
                'category_id' => '9',
                'brand_id' => '4',
                'title' => 'Royal London 20034-02 VQ - Ройял Лондон Часы 900',
                'alias' => 'royal-london-20034-02',
                'price' => 320,
                'old_price' => 220,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '1',
            ],
            [
                'id' => '10',
                'category_id' => '8',
                'brand_id' => '4',
                'title' => 'Royal London 41156-02 KVQ - - Ройял Лондон Часы ФВ 8',
                'alias' => 'royal-london-41156-02',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '1',
            ],


            [
                'id' => '11',
                'category_id' => '2',
                'brand_id' => '2',
                'title' => 'Swimming Watch VQ-01 - Часы для плавание в бассейне',
                'alias' => 'chasy-1',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],
            [
                'id' => '12',
                'category_id' => '2',
                'brand_id' => '2',
                'title' => 'Running Watch VQ-9 - Беговые часы на андроиде',
                'alias' => 'chasy-2',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

            [
                'id' => '13',
                'category_id' => '15',
                'brand_id' => '2',
                'title' => 'Android Watch BQ-1 - Андроид часы БКЬю',
                'alias' => 'chasy-3',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

            [
                'id' => '14',
                'category_id' => '13',
                'brand_id' => '2',
                'title' => 'Sport Watch BQ-009 - Часы спортивные Ультра',
                'alias' => 'chasy-4',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

            [
                'id' => '15',
                'category_id' => '16',
                'brand_id' => '2',
                'title' => 'Apple Watch B Sport - Эпл Часы 4',
                'alias' => 'chasy-5',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

            [
                'id' => '16',
                'category_id' => '12',
                'brand_id' => '2',
                'title' => 'Rolex Gold B For Water - Ролекс Голд Б для Плавания',
                'alias' => 'chasy-6',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

            [
                'id' => '17',
                'category_id' => '11',
                'brand_id' => '2',
                'title' => 'Sumsung Gear Pro F-sport - Самсунг Геар Про Ф Спорт',
                'alias' => 'chasy-7',
                'price' => 370,
                'old_price' => 250,
                'status' => '1',
                'keywords' => 'watch',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique, diam in consequat iaculis, est purus iaculis mauris, imperdiet facilisis ante ligula at nulla.',
                'img' => 'myasnik.jpg',
                'hit' => '0',
            ],

        ];

        DB::table('products')->insert($data);
    }
}
